# 1. SERVER CONFIG
server.port=8083

# H2 DATABASE CONFIG
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=false

# 3. JPA / HIBERNATE CONFIG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# 4. JWT CONFIG 
app.jwt.secret=QmVzdFByYWN0aWNlV2ViU2VydmljZVpEMjAyNFBvbHN0YXRTVEJTSmF3YXJhbnlhQXBpSldUU2VjdXJpdHlTdGlzQnJ1aA==
app.jwt.expiration-in-ms=86400000
